#global settings
timezone: Europe/Berlin

# Site settings
name: DIY14BUS
description: "Dies ist der Dokumentatiosblog des Projektes DIY14BUS als Teil der Vorlesung DIY: Personal Fabrication"
baseurl: "/diy14bus"
url: "https://michz.github.io/diy14bus/"
github:  michz/diy14bus

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false

# Build settings
markdown: kramdown
permalink: pretty

permalink: /:year/:month/:title
paginate: 3

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']

#author settings
#structure:
#    $USERNAME:
#        display_name: FULL NAME
#        gravatar: ID OF GRAVATAR (FOR PICTURE)
#        email: ADRESS
#        web: LINK TO WEBSITE
#        twitter: TWITTER USERNAME
#        github: GITHUB USERNAME

authors:
    pkanzler:
        display_name: Patrick Kanzler
        gravatar: 
        email: patrick.kanzler@fablab.fau.de
        web: 
        twitter: patrick_kanzler
        github: patkan
    mzapf:
        display_name: Michael Zapf
        gravatar: 
        email: 
        web: 
        twitter: 
        github: 
    rbackhaus:
        display_name: Robin Backhaus
        gravatar: 
        email: 
        web: 
        twitter: 
        github: 
    khoellring:
        display_name: Kevin Höllring
        gravatar: 
        email: 
        web: 
        twitter: 
        github: 
    jschnurrer:
        display_name: Josef Schnurrer
        gravatar: 
        email: 
        web: 
        twitter: 
        github: 
    diy14bus:
        display_name: DIY14BUS
        gravatar: 
        email: 
        web: michz.github.io/diy14bus/
        twitter:
        github: michz/diy14bus

     