# Site settings
title: DIY14BUS
email: 
description: "Dies ist die Dokumentationsseite des Projektes DIY14BUS als Teil der Vorlesung DIY: Presonal Fabrication"
baseurl: "/diy14bus"
url: "https://michz.github.io/diy14bus/"
twitter_username: n/a
github_username:  michz

# Build settings
markdown: kramdown
permalink: pretty
